catalogMode: prefer
ignoreWorkspaceRootCheck: true

shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - docs
  - packages/*/playground

catalog:
  '@antfu/eslint-config': ^8.1.1
  '@antfu/ni': ^30.0.0
  '@iconify-json/ri': ^1.2.10
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/markdown-it': ^4.0.2
  '@shikijs/transformers': ^4.0.2
  '@shikijs/twoslash': ^4.0.2
  '@shikijs/vitepress-twoslash': ^4.0.2
  '@types/eslint': ^9.6.1
  '@types/node': ^25.6.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@typescript/ata': ^0.9.8
  '@typescript/twoslash': ^3.2.12
  '@typescript/vfs': ^1.6.4
  '@unocss/reset': ^66.6.8
  '@vitest/coverage-v8': ^4.1.4
  '@vue/language-core': ^3.2.6
  '@vueuse/core': ^14.2.1
  bumpp: ^11.0.1
  chokidar: ^5.0.0
  eslint: ^10.2.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.3.0
  idb-keyval: ^6.2.2
  jiti: ^2.6.1
  lint-staged: ^16.4.0
  lz-string: ^1.5.0
  mlly: ^1.8.2
  ohash: ^2.0.11
  preact: ^10.29.1
  pretty-format: ^30.3.0
  react: ^19.2.5
  sass: ^1.99.0
  shiki: ^4.0.2
  simple-git-hooks: ^2.13.1
  tslib: ^2.8.1
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.6.8
  unplugin-vue-components: ^32.0.0
  unstorage: ^1.17.5
  vite: ^8.0.8
  vite-tsconfig-paths: ^6.1.1
  vitepress: ^2.0.0-alpha.17
  vitest: ^4.1.4
  vue: ^3.5.32
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
