catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - docs
  - packages/*/playground

catalog:
  '@antfu/eslint-config': ^6.7.1
  '@iconify-json/ri': ^1.2.6
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/markdown-it': ^3.20.0
  '@shikijs/transformers': ^3.20.0
  '@shikijs/twoslash': ^3.20.0
  '@shikijs/vitepress-twoslash': ^3.20.0
  '@types/eslint': ^9.6.1
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript/ata': ^0.9.8
  '@typescript/twoslash': ^3.2.10
  '@typescript/vfs': ^1.6.2
  '@unocss/reset': ^66.5.10
  '@vitest/coverage-v8': ^4.0.16
  '@vue/language-core': ^3.2.0
  '@vueuse/core': ^14.1.0
  bumpp: ^10.3.2
  eslint: ^9.39.2
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  idb-keyval: ^6.2.2
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  lz-string: ^1.5.0
  mlly: ^1.8.0
  ohash: ^2.0.11
  preact: ^10.28.0
  pretty-format: ^30.2.0
  react: ^19.2.3
  sass: ^1.97.1
  shiki: ^3.20.0
  simple-git-hooks: ^2.13.1
  tslib: ^2.8.1
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.10
  unplugin-vue-components: ^30.0.0
  unstorage: ^1.17.3
  vite: ^7.3.0
  vite-tsconfig-paths: ^6.0.3
  vitepress: ^2.0.0-alpha.15
  vitest: ^4.0.16
  vue: ^3.5.26

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
