packages:
  - packages/*
  - docs
  - packages/*/playground
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/markdown-it': ^3.0.0
  '@shikijs/transformers': ^3.0.0
  '@shikijs/twoslash': ^3.0.0
  '@shikijs/vitepress-twoslash': ^3.0.0
  '@types/eslint': ^9.6.1
  '@types/node': ^22.13.5
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@typescript/ata': ^0.9.7
  '@typescript/twoslash': ^3.2.9
  '@typescript/vfs': ^1.6.1
  '@vitest/coverage-v8': ^3.0.7
  '@unocss/reset': ^66.0.0
  '@vue/language-core': 2.2.4
  '@vueuse/core': ^12.7.0
  bumpp: ^10.0.3
  eslint: ^9.21.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  idb-keyval: ^6.2.1
  jiti: ^2.4.2
  lint-staged: ^15.4.3
  lz-string: ^1.5.0
  mlly: ^1.7.4
  ohash: ^2.0.5
  preact: ^10.26.2
  pretty-format: ^29.7.0
  react: ^19.0.0
  sass: ^1.85.1
  shiki: ^3.0.0
  simple-git-hooks: ^2.11.1
  tslib: ^2.8.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.0
  unstorage: ^1.15.0
  vite: ^6.2.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.7
  vitepress: ^2.0.0-alpha.3
  vue: ^3.5.13
